# Generated by Django 3.2.12 on 2024-07-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_promotion_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
