# Generated by Django 3.2.12 on 2024-08-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'В ожидании'), ('O', 'На доставке'), ('C', 'Успешно доставлен'), ('F', 'Отменено')], default='P', max_length=1),
        ),
    ]
