# Generated by Django 3.2.12 on 2024-05-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('language', models.CharField(blank=True, choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], max_length=2, null=True)),
                ('birth_date', models.DateField()),
                ('is_courier', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Users',
                'verbose_name_plural': 'User',
            },
        ),
    ]
