# Generated by Django 3.2.12 on 2024-04-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_url',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
