# Generated by Django 3.2.12 on 2024-04-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
